# Generated by Django 4.2.4 on 2023-08-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="series_number",
            field=models.IntegerField(null=True),
        ),
    ]
