# Generated by Django 4.2.4 on 2023-08-10 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_book_series_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="series_books",
                to="catalog.series",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="series_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
