# Generated by Django 4.2.4 on 2023-08-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_book_series_alter_book_series_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="author",
            new_name="authors",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="genre",
            new_name="genres",
        ),
    ]
