# Generated by Django 4.2.4 on 2023-08-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_rename_author_book_authors_rename_genre_book_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="total_books",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
