# Generated by Django 4.2.4 on 2023-08-12 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_series_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_series",
                to="catalog.author",
            ),
        ),
    ]
